name: chat_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  font_awesome_flutter: ^10.8.0
  dash_chat_2: ^0.0.21
  cupertino_icons: ^1.0.8

  # API Integration
  http: ^1.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:

 
  uses-material-design: true

  